package at.jku.ssw.openvc.ast;

public enum EntityClass {
	ENTITY, ARCHITECTURE, CONFIGURATION, PACKAGE, PROCEDURE, FUNCTION, TYPE, SUBTYPE, CONSTANT, SIGNAL, VARIABLE, FILE, COMPONENT, LABEL,
	  LITERAL, UNITS, GROUP, NATURE, SUBNATURE, QUANTITY, TERMINAL
}
